version: '3.9'

services:
  nginx:
    build: ./nginx
    ports:
     - "80:80"
    depends_on:
     - web1

  redis:
    image: redis:alpine
    restart: always
    ports:
     - "6379:6379"

  web1:
    build: ./web01
    ports:
     - "81:5000"
    depends_on: 
     - redis   
